name: json_pro
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/myConsciousness/json-pro

environment:
  sdk: ">=2.15.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  import_sorter: ^4.6.0
