name: json_response
description: A most easily usable JSON response wrapper library in Dart. With JsonResponse, you can easily and safely handle JSON response on your application.
version: 2.2.0
homepage: https://github.com/myConsciousness/json-response

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  import_sorter: ^4.6.0
